#!/bin/bash

help()
{
    echo
    echo "70mai Dash Cam Lite 2 timelapse and hud map video builder tool"
    echo "--- Soundtrack builder"
    echo
    echo "Syntax: $0 [option] [param] [option] [param] ..."
    echo
    echo "Options:"
    echo
    echo "      -h          Shows this help screen"
    echo
    echo "      -i DIR      Input dir from where to get audio files to build soundtrack (defaults to ${HOME}/Music/)"
    echo
    echo "      -l SECONDS  Target duration in seconds (required)"
    echo
    echo "      -o FILE     Output audio file (defaults to ./soundtrack.wav)"
    echo
}

INPUT="${HOME}/Music/"
OUTPUT="./soundtrack.wav"
LENGHT=-1

while getopts "hi:l:o:" option; do
    case $option in
        h)
            help
            exit;;
        i) 
            INPUT=$OPTARG
            ;;
        l) 
            LENGHT=$OPTARG
            ;;
        o) 
            OUTPUT=$OPTARG
            ;;
        \?)
            help
            exit;;
   esac
done

calculate_audio_length(){
    soxi -D "$1" 2>/dev/null
}

generateSoundtrack(){
    INPUT=$1
    LENGHT=$2
    OUTPUT=$3
    AUDIO_LENGTH=0
    MUSIC_FILES_COUNT=0
    ROUNDED_LENGTH=$(echo $LENGHT | sed 's/\.[0-9]*//g')

    TOTAL_LENGTH=0
    find $INPUT -type f | sort -R | while read FILE; do
        FILE_AUDIO_LENGTH=$(calculate_audio_length "$FILE")
        if [ -n "$FILE_AUDIO_LENGTH" ]; then 
            FILE_AUDIO_ROUNDED_LENGTH=$(echo $FILE_AUDIO_LENGTH | sed 's/\.[0-9]*//g')
            TOTAL_LENGTH=$((TOTAL_LENGTH+FILE_AUDIO_ROUNDED_LENGTH))

            if [ -n "$FILES" ]; then
                FILES="$FILES=$FILE"
            else
                FILES=$FILE
            fi

            if [ "$ROUNDED_LENGTH" -lt "$TOTAL_LENGTH" ]; then
                FILES="$FILES=$OUTPUT"
                IFS="="
                sox $FILES
                break
            fi
        fi
    done
}

if [ "$LENGHT" -gt "0" ]; then
    generateSoundtrack $INPUT $LENGHT $OUTPUT
else
    help
fi