#!/bin/sh

help()
{
    echo
    echo "70mai Dash Cam Lite 2 timelapse and hud map video builder tool"
    echo "--- PNG + Audio to encoded video"
    echo
    echo "Syntax: $0 [option] [param] [option] [param] ..."
    echo
    echo "Options:"
    echo
    echo "      -h          Shows this help screen"
    echo
    echo "      -i DIR      Input dir for PNG image sequence (required)"
    echo
    echo "      -a AUDIO    Audio file"
    echo
    echo "      -f FADE_IN  Fade in time in seconds"
    echo
    echo "      -x FADE_OUT Fade out time in seconds"
    echo
    echo "      -o FILE     Output video file (required)"
    echo
    exit
}

FPS=30
INPUT_DIR=""
AUDIO_FILE=""
FADE_IN=0
FADE_OUT=0
OUTPUT_FILE=""

while getopts "hi:a:f:x:o:" option; do
    case $option in
        h)
            help
            exit;;
        i)
            INPUT_DIR=$OPTARG
            ;;
        a)
            AUDIO_FILE=$OPTARG
            ;;
        f)
            FADE_IN=$OPTARG
            ;;
        x)
            FADE_OUT=$OPTARG
            ;;
        o)
            OUTPUT_FILE=$OPTARG
            ;;
        \?)
            help
            exit;;
   esac
done

if [ -z "$INPUT_DIR" ]; then
    echo "Input dir is required"
    help
fi

if [ -z "$OUTPUT_FILE" ]; then
    echo "Output file is required"
    help
fi

FILE_COUNT=$(ls -1q $INPUT_DIR/* | wc -l)
VIDEO_DURATION=$(($FILE_COUNT/$FPS))
FADE_OUT_START=`echo $VIDEO_DURATION - $FADE_OUT | bc`

FFMPEGARGSAUDIO=""
FFMPEGARGSAUDIOSHORTEST=""
if [ -n "$AUDIO_FILE" ]; then
    FFMPEGARGSAUDIO="-i $AUDIO_FILE"
    FFMPEGARGSAUDIOSHORT="-shortest"
fi

CMD="ffmpeg \
    -framerate $FPS \
    -i $INPUT_DIR/%06d.jpg \
    $FFMPEGARGSAUDIO \
    -vf fade=in:0:d=$FADE_IN,fade=out:$FADE_OUT_START:d=$FADE_OUT \
    -af afade=in:0:d=$FADE_IN,afade=out:$FADE_OUT_START:d=$FADE_OUT \
    -c:v libx265 -preset fast \
    -c:a aac -b:a 128k \
    $FFMPEGARGSAUDIOSHORTEST \
    $OUTPUT_FILE"

CMD="ffmpeg \
    -framerate $FPS \
    -i $INPUT_DIR/%06d.jpg \
    $FFMPEGARGSAUDIO \
    -c:v libx265 -preset fast \
    -c:a aac -b:a 128k \
    $FFMPEGARGSAUDIOSHORTEST \
    $OUTPUT_FILE"

echo $CMD
"$CMD"